export const data = {
  "Generative AI": [
    {
      id: "gen-ai-everyone",
      name: "Generative AI for Everyone",
      duration: "8 Weeks",
      startDate: "2nd May '25",
      image: "/generativeAi.webp",
      activeUsers: 120,
    },
    {
      id: "gans-workshop",
      name: "Hands-on GANs Workshop",
      duration: "6 Weeks",
      startDate: "7th May '25",
      image: "/ganAi.png",
      activeUsers: 120,
    },
    {
      id: "llm-practice",
      name: "Large Language Models in Practice",
      duration: "10 Weeks",
      startDate: "10th May '25",
      image: "/llmAi.webp",
      activeUsers: 120,
    },
    {
      id: "prompt-engineering",
      name: "Prompt Engineering Fundamentals",
      duration: "4 Weeks",
      startDate: "15th May '25",
      image: "/promptEngineering.jpg",
      activeUsers: 120,
    },
    {
      id: "nlp-transformers",
      name: "NLP with Transformers",
      duration: "3 Months",
      startDate: "20th May '25",
      image: "/nlpAi.jpg",
      activeUsers: 120,
    },
  ],
  "AI & Machine Learning": [
    {
      id: "ml-bootcamp",
      name: "Machine Learning Bootcamp",
      duration: "6 Months",
      startDate: "1st May '25",
      activeUsers: 120,
      image: "/machineLearningImage.jpg",
    },
    {
      id: "ai-business-leaders",
      name: "AI for Business Leaders",
      duration: "3 Months",
      startDate: "5th May '25",
      activeUsers: 120,
      image: "/aiBusiness.jpg",
    },
    {
      id: "deep-learning-tensorflow",
      name: "Deep Learning with TensorFlow",
      duration: "5 Months",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/tensorFlow.jpg",
    },
    {
      id: "ml-model-deployment",
      name: "ML Model Deployment",
      duration: "2 Months",
      startDate: "15th May '25",
      image: "/modelDevelopment.webp",
      activeUsers: 120,
    },
    {
      id: "ai-strategy-ethics",
      name: "AI Strategy & Ethics",
      duration: "6 Weeks",
      startDate: "20th May '25",
      image: "/aiEthics.webp",
      activeUsers: 120,
    },
  ],
  "Data Science & Business Analytics": [
    {
      id: "data-analyst",
      name: "Data Analyst",
      duration: "11 Months",
      startDate: "26th Apr '25",
      image: "/dataAnalyst.webp",
      activeUsers: 120,
    },
    {
      id: "business-analyst",
      name: "Business Analyst",
      duration: "11 Months",
      startDate: "22nd Apr '25",
      image: "/businessAnalyst.avif",
      activeUsers: 120,
    },
    {
      id: "data-science-python",
      name: "Data Science with Python",
      duration: "6 Months",
      startDate: "5th May '25",
      image: "/pythonDataScience.jpg",
      activeUsers: 120,
    },
    {
      id: "power-bi-data-insights",
      name: "Power BI for Data Insights",
      duration: "8 Weeks",
      startDate: "10th May '25",
      image: "/powerBi.jpg",
      activeUsers: 120,
    },
    {
      id: "statistics-business",
      name: "Statistics for Business",
      duration: "2 Months",
      startDate: "12th May '25",
      image: "/businessStatics.avif",
      activeUsers: 120,
    },
  ],
  "Project Management": [
    {
      id: "pmp-certification",
      name: "PMP® Certification Training",
      duration: "4 Weeks",
      startDate: "22nd Apr '25",
      image: "/pmpTraning.jpg",
      activeUsers: 120,
    },
    {
      id: "agile-project-management",
      name: "Agile Project Management",
      duration: "6 Weeks",
      startDate: "1st May '25",
      activeUsers: 120,
      image: "/aglieManagement.jpg",
    },
    {
      id: "pgmp-certification-training",
      name: "Program Management Professional (PgMP®)",
      duration: "3 Months",
      startDate: "7th May '25",
      activeUsers: 120,
      image: "/pgmp.jpg",
    },
    {
      id: "ms-project-training",
      name: "MS Project Training",
      duration: "4 Weeks",
      startDate: "11th May '25",
      activeUsers: 120,
      image: "/MspProject.png",
    },
    {
      id: "project-risk-management",
      name: "Project Risk Management",
      duration: "5 Weeks",
      startDate: "17th May '25",
      activeUsers: 120,
      image: "/riskManagement.webp",
    },
  ],
  "Cyber Security": [
    {
      id: "executive-cybersecurity-program",
      name: "Advanced Executive Program in Cybersecurity",
      duration: "6 Months",
      startDate: "23rd Apr '25",
      activeUsers: 120,
      image: "/cyber.jpg",
    },
    {
      id: "ethical-hacking-training",
      name: "Ethical Hacking Training",
      duration: "4 Months",
      startDate: "28th Apr '25",
      activeUsers: 120,
      image: "/ethicalHacking.webp",
    },
    {
      id: "network-security-specialist",
      name: "Network Security Specialist",
      duration: "10 Weeks",
      startDate: "2nd May '25",
      activeUsers: 120,
      image: "/NetworkSecurity.png",
    },
    {
      id: "cloud-security-basics",
      name: "Cloud Security Basics",
      duration: "2 Months",
      startDate: "6th May '25",
      activeUsers: 120,
      image: "/cloudSecurity.jpeg",
    },
    {
      id: "cyber-threat-intelligence",
      name: "Cyber Threat Intelligence",
      duration: "3 Months",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/cyberThreat.jpg",
    },
  ],
  "Agile and Scrum": [
    {
      id: "certified-scrummaster-csm",
      name: "Certified ScrumMaster® (CSM)",
      duration: "3 Days",
      startDate: "23rd Apr '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "safe-agilist-certification",
      name: "SAFe® Agilist Certification",
      duration: "2 Weeks",
      startDate: "30th Apr '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "agile-fundamentals",
      name: "Agile Fundamentals",
      duration: "1 Month",
      startDate: "5th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "scrum-product-owner",
      name: "Scrum Product Owner",
      duration: "2 Weeks",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "agile-for-teams",
      name: "Agile for Teams",
      duration: "3 Weeks",
      startDate: "12th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Cloud Computing & DevOps": [
    {
      id: "cloud-architect-program",
      name: "Cloud Architect Program",
      duration: "12 Months",
      startDate: "6th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "aws-solutions-architect",
      name: "AWS Solutions Architect",
      duration: "4 Months",
      startDate: "10th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "devops-certification",
      name: "DevOps Engineer Certification",
      duration: "6 Months",
      startDate: "14th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "kubernetes-for-developers",
      name: "Kubernetes for Developers",
      duration: "3 Months",
      startDate: "17th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "azure-fundamentals",
      name: "Azure Fundamentals",
      duration: "8 Weeks",
      startDate: "20th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Business and Leadership": [
    {
      id: "executive-leadership",
      name: "Executive Leadership Program",
      duration: "8 Months",
      startDate: "10th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "strategic-thinking",
      name: "Strategic Thinking for Leaders",
      duration: "3 Months",
      startDate: "14th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "business-communication",
      name: "Business Communication Mastery",
      duration: "6 Weeks",
      startDate: "18th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "change-management",
      name: "Change Management",
      duration: "2 Months",
      startDate: "22nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "innovation-growth",
      name: "Innovation and Growth",
      duration: "1 Month",
      startDate: "25th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Software Development": [
    {
      id: "full-stack-developer",
      name: "Full Stack Developer Course",
      duration: "9 Months",
      startDate: "15th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "frontend-development-react",
      name: "Frontend Development with React",
      duration: "4 Months",
      startDate: "20th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "backend-development-nodejs",
      name: "Backend Development with Node.js",
      duration: "5 Months",
      startDate: "24th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "software-engineering-principles",
      name: "Software Engineering Principles",
      duration: "6 Weeks",
      startDate: "28th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "clean-code-architecture",
      name: "Clean Code and Architecture",
      duration: "3 Months",
      startDate: "30th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Product and Design": [
    {
      id: "ux-ui-design-certification",
      name: "UX/UI Design Certification",
      duration: "6 Months",
      startDate: "5th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "figma-masterclass",
      name: "Figma Masterclass",
      duration: "2 Months",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "design-thinking-innovation",
      name: "Design Thinking for Innovation",
      duration: "4 Weeks",
      startDate: "13th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "interaction-design-essentials",
      name: "Interaction Design Essentials",
      duration: "3 Months",
      startDate: "17th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "prototyping-usability-testing",
      name: "Prototyping & Usability Testing",
      duration: "1 Month",
      startDate: "22nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "IT Service and Architecture": [
    {
      id: "itil-4-foundation",
      name: "ITIL® 4 Foundation Certification",
      duration: "2 Weeks",
      startDate: "3rd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "enterprise-architecture-fundamentals",
      name: "Enterprise Architecture Fundamentals",
      duration: "2 Months",
      startDate: "8th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "it-service-management-servicenow",
      name: "IT Service Management with ServiceNow",
      duration: "3 Months",
      startDate: "13th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "agile-itsm-practices",
      name: "Agile ITSM Practices",
      duration: "6 Weeks",
      startDate: "18th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "it-strategy-governance",
      name: "IT Strategy and Governance",
      duration: "5 Weeks",
      startDate: "22nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Quality Management": [
    {
      id: "six-sigma-green-belt",
      name: "Six Sigma Green Belt Certification",
      duration: "1 Month",
      startDate: "4th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "lean-six-sigma-yellow-belt",
      name: "Lean Six Sigma Yellow Belt",
      duration: "2 Weeks",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "quality-management-systems",
      name: "Quality Management Systems",
      duration: "2 Months",
      startDate: "13th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "iso-9001-2015-training",
      name: "ISO 9001:2015 Training",
      duration: "4 Weeks",
      startDate: "18th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "root-cause-analysis-workshop",
      name: "Root Cause Analysis Workshop",
      duration: "3 Weeks",
      startDate: "23rd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Digital Marketing": [
    {
      id: "digital-marketing-specialist-program",
      name: "Digital Marketing Specialist Program",
      duration: "7 Months",
      startDate: "8th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "seo-sem-fundamentals",
      name: "SEO & SEM Fundamentals",
      duration: "2 Months",
      startDate: "12th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "social-media-marketing",
      name: "Social Media Marketing",
      duration: "3 Months",
      startDate: "16th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "content-strategy-bootcamp",
      name: "Content Strategy Bootcamp",
      duration: "4 Weeks",
      startDate: "21st May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "google-ads-analytics",
      name: "Google Ads & Analytics",
      duration: "1 Month",
      startDate: "25th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
};
