export const data = {
  "Generative AI": [
    {
      id: "gen-ai-everyone",
      name: "Generative AI for Everyone",
      duration: "8 Weeks",
      startDate: "2nd May '25",
      image: "/generativeAi.webp",
      activeUsers: 120,
    },
    {
      id: "gans-workshop",
      name: "Hands-on GANs Workshop",
      duration: "6 Weeks",
      startDate: "7th May '25",
      image: "/generativeAi.webp",
      activeUsers: 120,
    },
    {
      id: "llm-practice",
      name: "Large Language Models in Practice",
      duration: "10 Weeks",
      startDate: "10th May '25",
      image: "/generativeAi.webp",
      activeUsers: 120,
    },
    {
      id: "prompt-engineering",
      name: "Prompt Engineering Fundamentals",
      duration: "4 Weeks",
      startDate: "15th May '25",
      image: "/generativeAi.webp",
      activeUsers: 120,
    },
    {
      id: "nlp-transformers",
      name: "NLP with Transformers",
      duration: "3 Months",
      startDate: "20th May '25",
      image: "/generativeAi.webp",
      activeUsers: 120,
    },
  ],
  "AI & Machine Learning": [
    {
      id: "ml-bootcamp",
      name: "Machine Learning Bootcamp",
      duration: "6 Months",
      startDate: "1st May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "ai-business-leaders",
      name: "AI for Business Leaders",
      duration: "3 Months",
      startDate: "5th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "deep-learning-tensorflow",
      name: "Deep Learning with TensorFlow",
      duration: "5 Months",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      id: "ml-model-deployment",
      name: "ML Model Deployment",
      duration: "2 Months",
      startDate: "15th May '25",
      image: "/ai-ml.jpg",
      activeUsers: 120,
    },
    {
      id: "ai-strategy-ethics",
      name: "AI Strategy & Ethics",
      duration: "6 Weeks",
      startDate: "20th May '25",
      image: "/ai-ml.jpg",
      activeUsers: 120,
    },
  ],
  "Data Science & Business Analytics": [
    {
      id: "data-analyst",
      name: "Data Analyst",
      duration: "11 Months",
      startDate: "26th Apr '25",
      image: "/dataScience.jpg",
      activeUsers: 120,
    },
    {
      id: "business-analyst",
      name: "Business Analyst",
      duration: "11 Months",
      startDate: "22nd Apr '25",
      image: "/dataScience.jpg",
      activeUsers: 120,
    },
    {
      id: "data-science-python",
      name: "Data Science with Python",
      duration: "6 Months",
      startDate: "5th May '25",
      image: "/dataScience.jpg",
      activeUsers: 120,
    },
    {
      id: "power-bi-data-insights",
      name: "Power BI for Data Insights",
      duration: "8 Weeks",
      startDate: "10th May '25",
      image: "/dataScience.jpg",
      activeUsers: 120,
    },
    {
      id: "statistics-business",
      name: "Statistics for Business",
      duration: "2 Months",
      startDate: "12th May '25",
      image: "/dataScience.jpg",
      activeUsers: 120,
    },
  ],
  "Project Management": [
    {
      name: "PMP® Certification Training",
      duration: "4 Weeks",
      startDate: "22nd Apr '25",
      image: "/ai-ml.jpg",
      activeUsers: 120,
    },
    {
      name: "Agile Project Management",
      duration: "6 Weeks",
      startDate: "1st May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Program Management Professional (PgMP®)",
      duration: "3 Months",
      startDate: "7th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "MS Project Training",
      duration: "4 Weeks",
      startDate: "11th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Project Risk Management",
      duration: "5 Weeks",
      startDate: "17th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Cyber Security": [
    {
      name: "Advanced Executive Program in Cybersecurity",
      duration: "6 Months",
      startDate: "23rd Apr '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Ethical Hacking Training",
      duration: "4 Months",
      startDate: "28th Apr '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Network Security Specialist",
      duration: "10 Weeks",
      startDate: "2nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Cloud Security Basics",
      duration: "2 Months",
      startDate: "6th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Cyber Threat Intelligence",
      duration: "3 Months",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Agile and Scrum": [
    {
      name: "Certified ScrumMaster® (CSM)",
      duration: "3 Days",
      startDate: "23rd Apr '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "SAFe® Agilist Certification",
      duration: "2 Weeks",
      startDate: "30th Apr '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Agile Fundamentals",
      duration: "1 Month",
      startDate: "5th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Scrum Product Owner",
      duration: "2 Weeks",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Agile for Teams",
      duration: "3 Weeks",
      startDate: "12th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Cloud Computing & DevOps": [
    {
      name: "Cloud Architect Program",
      duration: "12 Months",
      startDate: "6th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "AWS Solutions Architect",
      duration: "4 Months",
      startDate: "10th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "DevOps Engineer Certification",
      duration: "6 Months",
      startDate: "14th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Kubernetes for Developers",
      duration: "3 Months",
      startDate: "17th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Azure Fundamentals",
      duration: "8 Weeks",
      startDate: "20th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Business and Leadership": [
    {
      name: "Executive Leadership Program",
      duration: "8 Months",
      startDate: "10th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Strategic Thinking for Leaders",
      duration: "3 Months",
      startDate: "14th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Business Communication Mastery",
      duration: "6 Weeks",
      startDate: "18th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Change Management",
      duration: "2 Months",
      startDate: "22nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Innovation and Growth",
      duration: "1 Month",
      startDate: "25th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Software Development": [
    {
      name: "Full Stack Developer Course",
      duration: "9 Months",
      startDate: "15th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Frontend Development with React",
      duration: "4 Months",
      startDate: "20th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Backend Development with Node.js",
      duration: "5 Months",
      startDate: "24th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Software Engineering Principles",
      duration: "6 Weeks",
      startDate: "28th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Clean Code and Architecture",
      duration: "3 Months",
      startDate: "30th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Product and Design": [
    {
      name: "UX/UI Design Certification",
      duration: "6 Months",
      startDate: "5th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Figma Masterclass",
      duration: "2 Months",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Design Thinking for Innovation",
      duration: "4 Weeks",
      startDate: "13th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Interaction Design Essentials",
      duration: "3 Months",
      startDate: "17th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Prototyping & Usability Testing",
      duration: "1 Month",
      startDate: "22nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "IT Service and Architecture": [
    {
      name: "ITIL® 4 Foundation Certification",
      duration: "2 Weeks",
      startDate: "3rd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Enterprise Architecture Fundamentals",
      duration: "2 Months",
      startDate: "8th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "IT Service Management with ServiceNow",
      duration: "3 Months",
      startDate: "13th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Agile ITSM Practices",
      duration: "6 Weeks",
      startDate: "18th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "IT Strategy and Governance",
      duration: "5 Weeks",
      startDate: "22nd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Quality Management": [
    {
      name: "Six Sigma Green Belt Certification",
      duration: "1 Month",
      startDate: "4th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Lean Six Sigma Yellow Belt",
      duration: "2 Weeks",
      startDate: "9th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Quality Management Systems",
      duration: "2 Months",
      startDate: "13th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "ISO 9001:2015 Training",
      duration: "4 Weeks",
      startDate: "18th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Root Cause Analysis Workshop",
      duration: "3 Weeks",
      startDate: "23rd May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
  "Digital Marketing": [
    {
      name: "Digital Marketing Specialist Program",
      duration: "7 Months",
      startDate: "8th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "SEO & SEM Fundamentals",
      duration: "2 Months",
      startDate: "12th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Social Media Marketing",
      duration: "3 Months",
      startDate: "16th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Content Strategy Bootcamp",
      duration: "4 Weeks",
      startDate: "21st May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
    {
      name: "Google Ads & Analytics",
      duration: "1 Month",
      startDate: "25th May '25",
      activeUsers: 120,
      image: "/ai-ml.jpg",
    },
  ],
};
