import { CoursesContentProps } from "../../types";
import { Gans, GenAI, Llm, Nlp, Prompt } from "./generativeAi";
import {
  AiBusiness,
  AiStrategy,
  DeepLearning,
  MlBootcamp,
  MlModel,
} from "./aiAndMl";
import {
  BusinessAnalyst,
  DataAnalyst,
  DataSciencePy,
  PowerBiInsights,
  StatisticsBusiness,
} from "./dataSciAndBusinessAna";
import {
  AgileProject,
  MsProject,
  PgmpTraining,
  PmpTraining,
  ProjectRisk,
} from "./projectManagement";
import { getBannerFeatures } from "../common";
import {
  AdvancedExecutiveProgram,
  CloudSecurityBasics,
  CyberThreatIntelligence,
  EthicalHackingTraining,
  NetworkSecuritySpecialist,
} from "./cyberSecurity";
import {
  AgileForTeams,
  AgileFundamentals,
  SafeAgilist,
  ScrumMaster,
  ScrumProductOwner,
} from "./aglieAndScrum";
import {
  AgileITSMPractices,
  EnterpriseArchitecture,
  Itil4Foundation,
  ITServiceManagement,
  ITStrategyAndGovernance,
} from "./itServiceAndArchitecture";
import {
  ISO9001Training,
  LeanSixSigmaYellowBelt,
  QualityManagementSystems,
  RootCauseAnalysis,
  SixSigmaGreenBelt,
} from "./qualityManagement";
import {
  ContentStrategyBootcamp,
  DigitalMarketingSpecialist,
  GoogleAdsAnalytics,
  SeoSemFundamentals,
  SocialMediaMarketing,
} from "./digitalMarketing";
import {
  AwsSolutions,
  AzureFundamentals,
  CloudArchitect,
  DevOpsEngineer,
  Kubernetes,
} from "./cloudCompAndDevOps";
import {
  DesignThinking,
  FigmaMasterclass,
  InteractionDesign,
  PrototypingUsability,
  UxUi,
} from "./productAndDesign";
import {
  CleanCodeArchitecture,
  FullStackDev,
  NodejsBackendDev,
  ReactFrontendDev,
  SoftwareEngineering,
} from "./softwareDevelopment";
import {
  BusinessCommunication,
  ChangeManagement,
  ExecutiveLeadership,
  Innovation,
  StrategicThinking,
} from "./businessAndLeadership";

export const exploreProgramsStack: CoursesContentProps[] = [
  {
    id: "gen-ai-everyone",
    techName: "Generative AI for Everyone",
    bannerFeatures: getBannerFeatures("8 Weeks"),
    courseFeatures: GenAI.courseFeatures,
    useCases: GenAI.useCases,
    tagline:
      "Understand the foundations of generative AI and how it's transforming industries with real-world applications.",
    career: GenAI.career,
    howItWorks: GenAI.howItWorks,
  },
  {
    id: "gans-workshop",
    techName: "Hands-on GANs Workshop",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    courseFeatures: Gans.courseFeatures,
    useCases: Gans.useCases,
    tagline:
      "Dive deep into Generative Adversarial Networks (GANs) and gain hands-on experience building and training your own models.",
    career: Gans.career,
    howItWorks: Gans.howItWorks,
  },
  {
    id: "llm-practice",
    techName: "Large Language Models in Practice",
    bannerFeatures: getBannerFeatures("10 Weeks"),
    courseFeatures: Llm.courseFeatures,
    useCases: Llm.useCases,
    tagline:
      "Learn to fine-tune and deploy Large Language Models (LLMs) for real-world applications using state-of-the-art tools and frameworks.",
    career: Llm.career,
    howItWorks: Llm.howItWorks,
  },
  {
    id: "prompt-engineering",
    techName: "Prompt Engineering Fundamentals",
    bannerFeatures: getBannerFeatures("4 Weeks"),
    courseFeatures: Prompt.courseFeatures,
    useCases: Prompt.useCases,
    tagline:
      "Master the art of prompt engineering to build powerful interactions with generative AI models like ChatGPT and Claude.",
    career: Prompt.career,
    howItWorks: Prompt.howItWorks,
  },
  {
    id: "nlp-transformers",
    techName: "NLP with Transformers",
    bannerFeatures: getBannerFeatures("3 Months"),
    courseFeatures: Nlp.courseFeatures,
    useCases: Nlp.useCases,
    tagline:
      "Build and fine-tune state-of-the-art NLP models using transformer architectures like BERT, GPT, and T5.",
    career: Nlp.career,
    howItWorks: Nlp.howItWorks,
  },
  {
    id: "ml-bootcamp",
    techName: "Machine Learning Bootcamp",
    bannerFeatures: getBannerFeatures("6 Months"),
    tagline:
      "Master machine learning fundamentals and build end-to-end models from data preprocessing to deployment.",
    howItWorks: MlBootcamp.howItWorks,
    courseFeatures: MlBootcamp.courseFeatures,
    useCases: MlBootcamp.useCases,
    career: MlBootcamp.career,
  },
  {
    id: "ai-business-leaders",
    techName: "AI for Business Leaders",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Gain the strategic and operational knowledge to lead AI transformation in your organization.",
    howItWorks: AiBusiness.howItWorks,
    courseFeatures: AiBusiness.courseFeatures,
    useCases: AiBusiness.useCases,
    career: AiBusiness.career,
  },
  {
    id: "deep-learning-tensorflow",
    techName: "Deep Learning with TensorFlow",
    bannerFeatures: getBannerFeatures("5 Months"),
    tagline:
      "Build neural networks using TensorFlow and master deep learning concepts through practical labs and projects.",
    howItWorks: DeepLearning.howItWorks,
    courseFeatures: DeepLearning.courseFeatures,
    useCases: DeepLearning.useCases,
    career: DeepLearning.career,
  },
  {
    id: "ml-model-deployment",
    techName: "ML Model Deployment",
    bannerFeatures: getBannerFeatures("2 Months"),
    tagline:
      "Learn to containerize, serve, and monitor ML models in production environments.",
    howItWorks: MlModel.howItWorks,
    courseFeatures: MlModel.courseFeatures,
    useCases: MlModel.useCases,
    career: MlModel.career,
  },
  {
    id: "ai-strategy-ethics",
    techName: "AI Strategy & Ethics",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    tagline:
      "Understand the ethical frameworks and strategic planning needed to responsibly implement AI across industries.",
    howItWorks: AiStrategy.howItWorks,
    courseFeatures: AiStrategy.courseFeatures,
    useCases: AiStrategy.useCases,
    career: AiStrategy.career,
  },
  {
    id: "data-analyst",
    techName: "Data Analyst",
    bannerFeatures: getBannerFeatures("11 Months"),
    tagline:
      "Master core data skills to extract, analyze, and visualize business insights using modern tools.",
    courseFeatures: DataAnalyst.courseFeatures,
    useCases: DataAnalyst.useCases,
    career: DataAnalyst.career,
    howItWorks: DataAnalyst.howItWorks,
  },
  {
    id: "business-analyst",
    techName: "Business Analyst",
    bannerFeatures: getBannerFeatures("11 Months"),
    tagline:
      "Bridge business goals and data insights to drive strategic decisions.",
    courseFeatures: BusinessAnalyst.courseFeatures,
    useCases: BusinessAnalyst.useCases,
    career: BusinessAnalyst.career,
    howItWorks: BusinessAnalyst.howItWorks,
  },
  {
    id: "data-science-python",
    techName: "Data Science with Python",
    bannerFeatures: getBannerFeatures("6 Months"),
    tagline:
      "Build a data science career by mastering Python, statistics, and machine learning.",
    courseFeatures: DataSciencePy.courseFeatures,
    useCases: DataSciencePy.useCases,
    career: DataSciencePy.career,
    howItWorks: DataSciencePy.howItWorks,
  },
  {
    id: "power-bi-data-insights",
    techName: "Power BI for Data Insights",
    bannerFeatures: getBannerFeatures("8 Weeks"),
    tagline: "Transform raw data into powerful visual stories with Power BI.",
    courseFeatures: PowerBiInsights.courseFeatures,
    useCases: PowerBiInsights.useCases,
    career: PowerBiInsights.career,
    howItWorks: PowerBiInsights.howItWorks,
  },
  {
    id: "statistics-business",
    techName: "Statistics for Business",
    bannerFeatures: getBannerFeatures("2 Months"),
    tagline:
      "Master statistical reasoning to make confident, data-driven decisions.",
    courseFeatures: StatisticsBusiness.courseFeatures,
    useCases: StatisticsBusiness.useCases,
    career: StatisticsBusiness.career,
    howItWorks: StatisticsBusiness.howItWorks,
  },
  {
    id: "pmp-certification",
    techName: "PMP® Certification Training",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Become a certified Project Management Professional (PMP®) by mastering project management skills, tools, and techniques.",
    courseFeatures: PmpTraining.courseFeatures,
    useCases: PmpTraining.useCases,
    career: PmpTraining.career,
    howItWorks: PmpTraining.howItWorks,
  },
  {
    id: "agile-project-management",
    techName: "Agile Project Management",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master Agile methodologies and frameworks, and build the skills to manage projects efficiently with Agile principles.",
    courseFeatures: AgileProject.courseFeatures,
    useCases: AgileProject.useCases,
    career: AgileProject.career,
    howItWorks: AgileProject.howItWorks,
  },
  {
    id: "pgmp-certification-training",
    techName: "Program Management Professional (PgMP®)",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Advance your career with PgMP® certification—designed for senior-level project professionals managing multiple programs.",
    courseFeatures: PgmpTraining.courseFeatures,
    useCases: PgmpTraining.useCases,
    career: PgmpTraining.career,
    howItWorks: PgmpTraining.howItWorks,
  },
  {
    id: "ms-project-training",
    techName: "MS Project Training",
    bannerFeatures: getBannerFeatures("2 Months"),
    tagline:
      "Master Microsoft Project to plan, execute, and control projects effectively using industry-standard tools.",
    courseFeatures: MsProject.courseFeatures,
    useCases: MsProject.useCases,
    career: MsProject.career,
    howItWorks: MsProject.howItWorks,
  },
  {
    id: "project-risk-management",
    techName: "Project Risk Management",
    bannerFeatures: getBannerFeatures("2 Months"),
    tagline:
      "Identify, analyze, and manage project risks with proactive strategies and real-world application.",
    courseFeatures: ProjectRisk.courseFeatures,
    useCases: ProjectRisk.useCases,
    career: ProjectRisk.career,
    howItWorks: ProjectRisk.howItWorks,
  },
  {
    id: "executive-cybersecurity-program",
    techName: "Advanced Executive Program in Cybersecurity",
    bannerFeatures: getBannerFeatures("6 Months"),
    tagline:
      "Transform your cybersecurity leadership with executive-level skills in risk, compliance, and cyber defense strategy.",
    courseFeatures: AdvancedExecutiveProgram.courseFeatures,
    useCases: AdvancedExecutiveProgram.useCases,
    career: AdvancedExecutiveProgram.career,
    howItWorks: AdvancedExecutiveProgram.howItWorks,
  },
  {
    id: "ethical-hacking-training",
    techName: "Ethical Hacking Training",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master ethical hacking skills to legally assess, penetrate, and secure systems from cyber threats.",
    courseFeatures: EthicalHackingTraining.courseFeatures,
    useCases: EthicalHackingTraining.useCases,
    career: EthicalHackingTraining.career,
    howItWorks: EthicalHackingTraining.howItWorks,
  },
  {
    id: "network-security-specialist",
    techName: "Network Security Specialist",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Learn to design, implement, and secure networks from evolving cyber threats with expert-level training.",
    courseFeatures: NetworkSecuritySpecialist.courseFeatures,
    useCases: NetworkSecuritySpecialist.useCases,
    career: NetworkSecuritySpecialist.career,
    howItWorks: NetworkSecuritySpecialist.howItWorks,
  },
  {
    id: "cloud-security-basics",
    techName: "Cloud Security Basics",
    bannerFeatures: getBannerFeatures("2 Months"),
    tagline:
      "Build a solid foundation in securing cloud environments and understanding key cloud security principles.",
    courseFeatures: CloudSecurityBasics.courseFeatures,
    useCases: CloudSecurityBasics.useCases,
    career: CloudSecurityBasics.career,
    howItWorks: CloudSecurityBasics.howItWorks,
  },
  {
    id: "cyber-threat-intelligence",
    techName: "Cyber Threat Intelligence",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master cyber threat analysis, intelligence gathering, and proactive defense strategies.",
    courseFeatures: CyberThreatIntelligence.courseFeatures,
    useCases: CyberThreatIntelligence.useCases,
    career: CyberThreatIntelligence.career,
    howItWorks: CyberThreatIntelligence.howItWorks,
  },
  {
    id: "certified-scrummaster-csm",
    techName: "Certified ScrumMaster® (CSM)",
    bannerFeatures: getBannerFeatures("2 Days"),
    tagline:
      "Become a certified Scrum Master and lead Agile teams to success with confidence and clarity.",
    courseFeatures: ScrumMaster.courseFeatures,
    useCases: ScrumMaster.useCases,
    career: ScrumMaster.career,
    howItWorks: ScrumMaster.howItWorks,
  },
  {
    id: "safe-agilist-certification",
    techName: "SAFe® Agilist Certification",
    bannerFeatures: getBannerFeatures("2 Days"),
    tagline:
      "Lead Agile transformation at scale with SAFe® and become a certified change agent in your organization.",
    courseFeatures: SafeAgilist.courseFeatures,
    useCases: SafeAgilist.useCases,
    career: SafeAgilist.career,
    howItWorks: SafeAgilist.howItWorks,
  },
  {
    id: "agile-fundamentals",
    techName: "Agile Fundamentals",
    bannerFeatures: getBannerFeatures("4 Weeks"),
    tagline:
      "Learn the core principles of Agile and how to apply them in real-world scenarios to drive continuous improvement.",
    courseFeatures: AgileFundamentals.courseFeatures,
    useCases: AgileFundamentals.useCases,
    career: AgileFundamentals.career,
    howItWorks: AgileFundamentals.howItWorks,
  },
  {
    id: "scrum-product-owner",
    techName: "Scrum Product Owner",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    tagline:
      "Master the role of a Scrum Product Owner and learn how to prioritize work, manage product backlogs, and deliver value-driven products.",
    courseFeatures: ScrumProductOwner.courseFeatures,
    useCases: ScrumProductOwner.useCases,
    career: ScrumProductOwner.career,
    howItWorks: ScrumProductOwner.howItWorks,
  },
  {
    id: "agile-for-teams",
    techName: "Agile for Teams",
    bannerFeatures: getBannerFeatures("4 Weeks"),
    tagline:
      "Equip your team with Agile methodologies to improve collaboration, adapt to changes, and deliver quality products efficiently.",
    courseFeatures: AgileForTeams.courseFeatures,
    useCases: AgileForTeams.useCase,
    career: AgileForTeams.career,
    howItWorks: AgileForTeams.howItWorks,
  },
  {
    id: "itil-4-foundation",
    techName: "ITIL® 4 Foundation Certification",
    bannerFeatures: getBannerFeatures("3 Weeks"),
    tagline:
      "Master ITIL® 4 Foundation principles to improve service management and align IT with business needs.",
    courseFeatures: Itil4Foundation.courseFeatures,
    useCases: Itil4Foundation.useCases,
    career: Itil4Foundation.career,
    howItWorks: Itil4Foundation.howItWorks,
  },
  {
    id: "enterprise-architecture-fundamentals",
    techName: "Enterprise Architecture Fundamentals",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    tagline:
      "Build a strong foundation in Enterprise Architecture to support business transformation and align IT strategy with business goals.",
    courseFeatures: EnterpriseArchitecture.courseFeatures,
    useCases: EnterpriseArchitecture.useCases,
    career: EnterpriseArchitecture.career,
    howItWorks: EnterpriseArchitecture.howItWorks,
  },
  {
    id: "it-service-management-servicenow",
    techName: "IT Service Management with ServiceNow",
    bannerFeatures: getBannerFeatures("8 Weeks"),
    tagline:
      "Learn how to implement and manage IT Service Management processes using ServiceNow to improve service delivery, streamline operations, and enhance customer experience.",
    courseFeatures: ITServiceManagement.courseFeatures,
    useCases: ITServiceManagement.useCases,
    career: ITServiceManagement.career,
    howItWorks: ITServiceManagement.howItWorks,
  },
  {
    id: "agile-itsm-practices",
    techName: "Agile ITSM Practices",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    tagline:
      "Master Agile practices tailored to IT Service Management (ITSM) to drive continuous improvement and accelerate service delivery.",
    courseFeatures: AgileITSMPractices.courseFeatures,
    useCases: AgileITSMPractices.useCases,
    career: AgileITSMPractices.career,
    howItWorks: AgileITSMPractices.howItWorks,
  },
  {
    id: "it-strategy-governance",
    techName: "IT Strategy and Governance",
    bannerFeatures: getBannerFeatures("8 Weeks"),
    tagline:
      "Develop strategic IT governance and management skills to align IT initiatives with business goals and drive transformation.",
    courseFeatures: ITStrategyAndGovernance.courseFeatures,
    useCases: ITStrategyAndGovernance.useCases,
    career: ITStrategyAndGovernance.career,
    howItWorks: ITStrategyAndGovernance.howItWorks,
  },
  {
    id: "six-sigma-green-belt",
    techName: "Six Sigma Green Belt Certification",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master Six Sigma methodologies to drive process improvement, reduce defects, and enhance organizational efficiency.",
    courseFeatures: SixSigmaGreenBelt.courseFeatures,
    useCases: SixSigmaGreenBelt.useCases,
    career: SixSigmaGreenBelt.career,
    howItWorks: SixSigmaGreenBelt.howItWorks,
  },
  {
    id: "lean-six-sigma-yellow-belt",
    techName: "Lean Six Sigma Yellow Belt",
    bannerFeatures: getBannerFeatures("1-2 Months"),
    tagline:
      "Gain foundational knowledge in Lean Six Sigma principles and contribute to process improvements at an organizational level.",
    courseFeatures: LeanSixSigmaYellowBelt.courseFeatures,
    useCases: LeanSixSigmaYellowBelt.useCases,
    career: LeanSixSigmaYellowBelt.career,
    howItWorks: LeanSixSigmaYellowBelt.howItWorks,
  },
  {
    id: "quality-management-systems",
    techName: "Quality Management Systems",
    bannerFeatures: getBannerFeatures("2-3 Months"),
    tagline:
      "Learn the principles and practices of quality management systems to enhance the effectiveness and efficiency of organizational processes.",
    courseFeatures: QualityManagementSystems.courseFeatures,
    useCases: QualityManagementSystems.useCases,
    career: QualityManagementSystems.career,
    howItWorks: QualityManagementSystems.howItWorks,
  },
  {
    id: "iso-9001-2015-training",
    techName: "ISO 9001:2015 Training",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master the principles of quality management and the ISO 9001:2015 standards to improve organizational processes and performance.",
    courseFeatures: ISO9001Training.courseFeatures,
    useCases: ISO9001Training.useCases,
    career: ISO9001Training.career,
    howItWorks: ISO9001Training.howItWorks,
  },
  {
    id: "root-cause-analysis-workshop",
    techName: "Root Cause Analysis Workshop",
    bannerFeatures: getBannerFeatures("2 Days"),
    tagline:
      "Learn to identify and analyze root causes of issues in your organization with hands-on exercises and practical tools.",
    courseFeatures: RootCauseAnalysis.courseFeatures,
    useCases: RootCauseAnalysis.useCases,
    career: RootCauseAnalysis.career,
    howItWorks: RootCauseAnalysis.howItWorks,
  },
  {
    id: "digital-marketing-specialist-program",
    techName: "Digital Marketing Specialist Program",
    bannerFeatures: getBannerFeatures("6 Months"),
    tagline:
      "Master the core digital marketing skills with hands-on projects and prepare for a rewarding career in marketing.",
    courseFeatures: DigitalMarketingSpecialist.courseFeatures,
    useCases: DigitalMarketingSpecialist.useCases,
    career: DigitalMarketingSpecialist.career,
    howItWorks: DigitalMarketingSpecialist.howItWorks,
  },
  {
    id: "seo-sem-fundamentals",
    techName: "SEO & SEM Fundamentals",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Gain a deep understanding of SEO and SEM to drive organic and paid traffic to websites and improve online visibility.",
    courseFeatures: SeoSemFundamentals.courseFeatures,
    useCases: SeoSemFundamentals.useCases,
    career: SeoSemFundamentals.career,
    howItWorks: SeoSemFundamentals.howItWorks,
  },
  {
    id: "social-media-marketing",
    techName: "Social Media Marketing",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master the art of building brand presence, engaging with audiences, and driving conversions on platforms like Facebook, Instagram, LinkedIn, and Twitter.",
    courseFeatures: SocialMediaMarketing.courseFeatures,
    useCases: SocialMediaMarketing.useCases,
    career: SocialMediaMarketing.career,
    howItWorks: SocialMediaMarketing.howItWorks,
  },
  {
    id: "content-strategy-bootcamp",
    techName: "Content Strategy Bootcamp",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Learn to craft compelling content strategies that drive engagement, align with business goals, and improve brand awareness and conversions.",
    courseFeatures: ContentStrategyBootcamp.courseFeatures,
    useCases: ContentStrategyBootcamp.useCases,
    career: ContentStrategyBootcamp.career,
    howItWorks: ContentStrategyBootcamp.howItWorks,
  },
  {
    id: "google-ads-analytics",
    techName: "Google Ads & Analytics",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master Google Ads and Google Analytics to effectively manage campaigns, measure performance, and optimize marketing strategies for better ROI.",
    courseFeatures: GoogleAdsAnalytics.courseFeatures,
    useCases: GoogleAdsAnalytics.useCases,
    career: GoogleAdsAnalytics.career,
    howItWorks: GoogleAdsAnalytics.howItWorks,
  },
  {
    id: "cloud-architect-program",
    techName: "Cloud Architect Program",
    bannerFeatures: getBannerFeatures("12 Months"),
    tagline:
      "Master multi-cloud infrastructure and architecture strategies to lead enterprise transformation.",
    howItWorks: CloudArchitect.howItWorks,
    courseFeatures: CloudArchitect.courseFeatures,
    useCases: CloudArchitect.useCases,
    career: CloudArchitect.career,
  },
  {
    id: "aws-solutions-architect",
    techName: "AWS Solutions Architect",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Become proficient in AWS services and design fault-tolerant, secure cloud systems.",
    howItWorks: AwsSolutions.howItWorks,
    courseFeatures: AwsSolutions.courseFeatures,
    useCases: AwsSolutions.useCases,
    career: AwsSolutions.career,
  },
  {
    id: "devops-certification",
    techName: "DevOps Engineer Certification",
    bannerFeatures: getBannerFeatures("6 Months"),
    tagline:
      "Learn CI/CD, containerization, and infrastructure automation to accelerate software delivery.",
    howItWorks: DevOpsEngineer.howItWorks,
    courseFeatures: DevOpsEngineer.courseFeatures,
    useCases: DevOpsEngineer.useCases,
    career: DevOpsEngineer.career,
  },
  {
    id: "kubernetes-for-developers",
    techName: "Kubernetes for Developers",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master Kubernetes fundamentals and apply them to real-world app development.",
    howItWorks: Kubernetes.howItWorks,
    courseFeatures: Kubernetes.courseFeatures,
    useCases: Kubernetes.useCases,
    career: Kubernetes.career,
  },
  {
    id: "azure-fundamentals",
    techName: "Azure Fundamentals",
    bannerFeatures: getBannerFeatures("8 Weeks"),
    tagline:
      "Gain foundational knowledge to confidently navigate Microsoft Azure cloud services.",
    howItWorks: AzureFundamentals.howItWorks,
    courseFeatures: AzureFundamentals.courseFeatures,
    useCases: AzureFundamentals.useCases,
    career: AzureFundamentals.career,
  },
  {
    id: "ux-ui-design-certification",
    techName: "UX/UI Design Certification",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Learn user-centric design, wireframing, prototyping, and tools like Figma and Adobe XD to become a UX/UI design professional.",
    courseFeatures: UxUi.courseFeatures,
    useCases: UxUi.useCases,
    career: UxUi.career,
    howItWorks: UxUi.howItWorks,
  },
  {
    id: "figma-masterclass",
    techName: "Figma Masterclass",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    tagline:
      "Master Figma for modern UI design—learn wireframing, prototyping, design systems, and collaboration workflows.",
    courseFeatures: FigmaMasterclass.courseFeatures,
    useCases: FigmaMasterclass.useCases,
    career: FigmaMasterclass.career,
    howItWorks: FigmaMasterclass.howItWorks,
  },
  {
    id: "design-thinking-innovation",
    techName: "Design Thinking for Innovation",
    bannerFeatures: getBannerFeatures("4 Weeks"),
    tagline:
      "Unlock creative problem-solving through a structured approach to innovation using human-centered design.",
    courseFeatures: DesignThinking.courseFeatures,
    useCases: DesignThinking.useCases,
    career: DesignThinking.career,
    howItWorks: DesignThinking.howItWorks,
  },
  {
    id: "interaction-design-essentials",
    techName: "Interaction Design Essentials",
    bannerFeatures: getBannerFeatures("5 Weeks"),
    tagline:
      "Master the principles of intuitive digital interactions and enhance user engagement through better design.",
    courseFeatures: InteractionDesign.courseFeatures,
    useCases: InteractionDesign.useCases,
    career: InteractionDesign.career,
    howItWorks: InteractionDesign.howItWorks,
  },
  {
    id: "prototyping-usability-testing",
    techName: "Prototyping & Usability Testing",
    bannerFeatures: getBannerFeatures("4 Weeks"),
    tagline:
      "Build interactive prototypes and conduct effective usability testing to create user-friendly designs.",
    courseFeatures: PrototypingUsability.courseFeatures,
    useCases: PrototypingUsability.useCases,
    career: PrototypingUsability.career,
    howItWorks: PrototypingUsability.howItWorks,
  },
  {
    id: "full-stack-developer",
    techName: "Full Stack Developer Course",
    bannerFeatures: getBannerFeatures("6 Months"),
    tagline:
      "Become a full-stack developer by mastering both front-end and back-end technologies, including JavaScript, Node.js, React, and more.",
    courseFeatures: FullStackDev.courseFeatures,
    useCases: FullStackDev.useCases,
    career: FullStackDev.career,
    howItWorks: FullStackDev.howItWorks,
  },
  {
    id: "frontend-development-react",
    techName: "Frontend Development with React",
    bannerFeatures: getBannerFeatures("3 Months"),
    tagline:
      "Master React.js and build dynamic, responsive web applications with industry-standard front-end tools and libraries.",
    courseFeatures: ReactFrontendDev.courseFeatures,
    useCases: ReactFrontendDev.useCases,
    career: ReactFrontendDev.career,
    howItWorks: ReactFrontendDev.howItWorks,
  },
  {
    id: "backend-development-nodejs",
    techName: "Backend Development with Node.js",
    bannerFeatures: getBannerFeatures("4 Months"),
    tagline:
      "Build scalable, server-side applications with Node.js, Express, and MongoDB to power modern web services.",
    courseFeatures: NodejsBackendDev.courseFeatures,
    useCases: NodejsBackendDev.useCases,
    career: NodejsBackendDev.career,
    howItWorks: NodejsBackendDev.howItWorks,
  },
  {
    id: "software-engineering-principles",
    techName: "Software Engineering Principles",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    tagline:
      "Master the core principles of software engineering to design, develop, and maintain high-quality software systems.",
    courseFeatures: SoftwareEngineering.courseFeatures,
    useCases: SoftwareEngineering.useCases,
    career: SoftwareEngineering.career,
    howItWorks: SoftwareEngineering.howItWorks,
  },
  {
    id: "clean-code-architecture",
    techName: "Clean Code and Architecture",
    bannerFeatures: getBannerFeatures("8 Weeks"),
    tagline:
      "Master clean code practices and software architecture principles to write maintainable and scalable applications.",
    courseFeatures: CleanCodeArchitecture.courseFeatures,
    useCases: CleanCodeArchitecture.useCases,
    career: CleanCodeArchitecture.career,
    howItWorks: CleanCodeArchitecture.howItWorks,
  },
  {
    id: "executive-leadership",
    techName: "Executive Leadership Program",
    bannerFeatures: getBannerFeatures("8 Months"),
    courseFeatures: ExecutiveLeadership.courseFeatures,
    useCases: ExecutiveLeadership.useCases,
    tagline:
      "Accelerate your leadership career with hands-on boardroom simulations and executive mentorship.",
    career: ExecutiveLeadership.career,
    howItWorks: ExecutiveLeadership.howItWorks,
  },
  {
    id: "strategic-thinking",
    techName: "Strategic Thinking for Leaders",
    bannerFeatures: getBannerFeatures("3 Months"),
    courseFeatures: StrategicThinking.courseFeatures,
    useCases: StrategicThinking.useCases,
    tagline:
      "Learn to think like a strategist and apply proven models to complex business decisions and growth challenges.",
    career: StrategicThinking.career,
    howItWorks: StrategicThinking.howItWorks,
  },
  {
    id: "business-communication",
    techName: "Business Communication Mastery",
    bannerFeatures: getBannerFeatures("6 Weeks"),
    courseFeatures: BusinessCommunication.courseFeatures,
    useCases: BusinessCommunication.useCases,
    tagline:
      "Master the art of professional communication—from writing and pitching to high-impact executive delivery.",
    career: BusinessCommunication.career,
    howItWorks: BusinessCommunication.howItWorks,
  },
  {
    id: "change-management",
    techName: "Change Management",
    bannerFeatures: getBannerFeatures("2 Months"),
    courseFeatures: ChangeManagement.courseFeatures,
    useCases: ChangeManagement.useCases,
    tagline:
      "Lead successful change initiatives with structured frameworks and real-world tools for organizational transformation.",
    career: ChangeManagement.career,
    howItWorks: ChangeManagement.howItWorks,
  },
  {
    id: "innovation-growth",
    techName: "Innovation and Growth",
    bannerFeatures: getBannerFeatures("i Month"),
    courseFeatures: Innovation.courseFeatures,
    useCases: Innovation.useCases,
    tagline:
      "Apply innovation frameworks to launch ideas, drive growth, and lead market-disrupting initiatives.",
    career: Innovation.career,
    howItWorks: Innovation.howItWorks,
  },
];
